---
ansible_ssh_pipelining: true

# root_prefix: ""

postgres_version: 9.4

default_archive_base_port: 6500
default_publishing_base_port: 6600
default_authoring_base_port: 6400


# postgres_connections:
#   - name: <human readable name>
#     addr: <hostname | ip | mask>
#     database: <default: all>
#     user: <default: all>
#     method: <default: trust>

# archive_db_name: cnxarchive
# archive_db_user: cnxarchive
# archive_db_password: cnxarchive
# archive_db_host: localhost
# archive_db_port: 5432

# memcached_hosts: localhost, foobar, goocar

# authoring_db_name: cnxauthoring
# authoring_db_user: cnxauthoring
# authoring_db_password: cnxauthoring
# authoring_db_host: localhost
# authoring_db_port: 5432

# archive_host: 0.0.0.0
# archive_port: 6789
# publishing_host: 0.0.0.0
# publishing_port: 6543
# authoring_host: 0.0.0.0
# authoring_port: 8080

# zope_domain: legacy.cnx.org
# arclishing_domain: archive.cnx.org
# frontend_domain: cnx.org
# accounts_domain: accounts.openstax.org
