---

# Note, the setup current **assumes** that the publishing and archive database
# is the same database. There has been no reason to split these yet, so we won't.

- name: initialize archive db
  command: "/usr/local/bin/initialize-archive-db {{ archive_db_host }} {{ archive_db_port }} {{ archive_db_name }} {{ archive_db_user }}"
