---
# Install HAProxy

- name: install haproxy
  become: yes
  apt:
    name: haproxy
    state: present
  notify:
    # rsyslog only picks up the newly added haproxy logging config after restart.
    - restart rsyslog

- name: configure haproxy ping monitoring
  become: yes
  blockinfile:
    dest: /etc/haproxy/haproxy.cfg
    state: present
    marker: "# {mark} ping monitoring block ANSIBLE MANAGED BLOCK"
    insertafter: "^\\s+errorfile 504 /etc/haproxy/errors/504.http"
    block: |
      {# Comment to let yml know where the indentation starts #}
        # Enable keep-alive connections towards the client,
        # but disable them towards the backend server
        option http-server-close
        # Remove requests from the queue if people press stop button
        option abortonclose
        # Try to connect this many times on failure
        retries 3
        # If a client is bound to a particular backend but it goes down,
        # send them to a different one
        option redispatch
        monitor-uri /haproxy-ping

        timeout connect 7s
        timeout queue   300s
        timeout client  300s
        timeout server  300s
        timeout check   10s

        # Enable status page at this URL, on the port HAProxy is bound to
        stats enable
        stats uri /haproxy-status
        stats refresh 5s
        stats realm Haproxy statistics
    owner: root
    group: root
    mode: 0644
  notify:
    - reload haproxy

- name: enable haproxy (trusty)
  become: yes
  when: ansible_distribution_release == "trusty"
  lineinfile:
    dest: /etc/default/haproxy
    regexp: 'ENABLED'
    line: 'ENABLED=1'
  notify:
    - restart haproxy
