---
- name: create zeopack wrapper script
  become: yes
  template:
    src: zeopack-wrapper.sh
    dest: "{{ zeopack_wrapper_filepath }}"
    owner: www-data
    group: www-data

- name: create zeopack cronjob
  become: yes
  cron:
    name: zeopack
    state: present
    special_time: weekly
    job: "{{ zeopack_wrapper_filepath }}"
    user: www-data
