language: python
python:
  - "2.7"
  - "3.6"
before_script:
  # pkg-resources not a package on pypi...
  # https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command
  - sed -i '/^pkg-resources==0/ D' environments/__prod_envs/files/*-requirements.txt
script:
  # Just testing that everything installs successfully with the right version of python
  - if [[ "${TRAVIS_PYTHON_VERSION:0:1}" == "2" ]]; then pip install -r environments/__prod_envs/files/archive-requirements.txt; fi
  - if [[ "${TRAVIS_PYTHON_VERSION:0:1}" == "2" ]]; then pip install -r environments/__prod_envs/files/publishing-requirements.txt; fi
  - if [[ "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]]; then pip install -r environments/__prod_envs/files/press-requirements.txt; fi

notifications:
  email: false
