language: python
python:
  - "2.7"
  - "3.6"
before_script:
  # pkg-resources not a package on pypi...
  # https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command
  - sed -i '/^pkg-resources==0/ D' environments/__prod_envs/files/*-requirements.txt
script:
  # Just testing that everything installs successfully with the right version of python
  - ./.travis-test.sh

notifications:
  email: false
