---

- name: package up source for shipment
  hosts: authoring
  vars:
    source:
      - name: cnx-query-grammar
        repo: https://github.com/Connexions/cnx-query-grammar.git
        default_version: HEAD
      - name: cnx-epub
        repo: https://github.com/Connexions/cnx-epub.git
        default_version: HEAD
      - name: openstax-accounts
        repo: https://github.com/Connexions/openstax-accounts.git
        default_version: HEAD
      - name: cnx-authoring
        repo: https://github.com/Connexions/cnx-authoring.git
        default_version: HEAD
  tasks:
    - name: install git
      become: yes
      apt:
        package: git
        state: present
    - name: make source directory
      become: yes
      file:
        path: "{{ source_dir }}"
        state: directory
        owner: www-data
        group: www-data
    - name: clone source
      become: yes
      become_user: www-data
      git:
        repo: "{{ item.repo }}"
        dest: "{{ source_dir }}/{{ item.name }}"
        version: "{{ (source_versions is defined and source_versions.get(item.name)) and source_versions[item.name] or item.default_version }}"
      with_items: "{{ source }}"
      register: git_result
      until: git_result|success
      retries: 5
      delay: 30

- name: install authoring
  hosts: authoring
  roles:
    - authoring
  tags:
    - authoring
    - be
