---
# Configure /etc/hosts file for development.

- include: pretask.yml

- name: "configure /etc/hosts file"
  hosts:
    - nfs
    - archive
    - publishing
    - authoring
    - lead_frontend
    - legacy_frontend
    - frontend
    - worker
    - database
    - zeo
    - zclient
    - pdf_gen
  tasks:
    - name: get dns from local /etc/hosts
      local_action: "command grep -E '\\<{{ accounts_domain }}\\>{% for group in groups.all %}|{{ '\\<%s\\>'|format(group) }}{% endfor %}' /etc/hosts"
      register: etc_hosts
    - name: remove old entries from target /etc/hosts
      become: yes
      lineinfile:
        dest: "/etc/hosts"
        regexp: "{{ item }}"
        state: absent
      with_items: "{{ groups.all }}"
    - name: add new entries to target /etc/hosts
      become: yes
      lineinfile:
        dest: "/etc/hosts"
        line: "{{ item }}"
        insertbefore: BOF
      with_items: "{{ etc_hosts.stdout_lines }}"
