---
# Playbook for configuration specific to Vagrant environment

- import_playbook: configure_hosts.yml

# NOTE: This is to help address firewall settings that prevent external access
# to dist.rhaptos.org. It expects an ssh tunnel on the Vagrant host to be
# running during provisioning. (See details in environments/vm/README.md)
- name: "configure dist.rhaptos.org in /etc/hosts"
  hosts:
    - zope
  tasks:
    - name: remove old rhaptos.org entries from target /etc/hosts
      become: yes
      lineinfile:
        dest: "/etc/hosts"
        regexp: "dist.rhaptos.org"
        state: absent
    - name: add rhaptos.org entry to target /etc/hosts
      become: yes
      lineinfile:
        dest: "/etc/hosts"
        line: "{{ rhaptos_tunnel_ip }} dist.rhaptos.org"
        insertbefore: BOF
