---
# Playbook for managing the database and replicant.

- name: install postgres database
  hosts:
    - database
    - replicant
  roles:
    - cnx_database
  tags:
    - database
    - be

- name: create databases and users
  hosts:
    - database
  tasks:
    - import_tasks: tasks/create_db_user.yml
      vars:
        db_user: "{{ archive_db_user }}"
        db_password: "{{ archive_db_password }}"
    - import_tasks: tasks/create_db.yml
      vars:
        db_owner: "{{ archive_db_user }}"
        db_name: "{{ archive_db_name }}"
    - import_tasks: tasks/create_db_user.yml
      when: authoring_db_user is defined
      vars:
        db_user: "{{ authoring_db_user }}"
        db_password: "{{ authoring_db_password }}"
    - import_tasks: tasks/create_db_user.yml
      vars:
        db_user: "backups"
        role_attr_flags: ""
    - import_tasks: tasks/create_db.yml
      when: authoring_db_user is defined
      vars:
        db_owner: "{{ authoring_db_user }}"
        db_name: "{{ authoring_db_name }}"
    - import_tasks: tasks/create_db_user.yml
      vars:
        db_user: "{{ replicator_db_user|default(default_replicator_db_user) }}"
        role_attr_flags: "replication"
  tags:
    - database
    - be

- name: set up replication on replicant
  hosts:
    - replicant
  roles:
    - postgres_replicant
  tags:
    - database
    - replication
    - be
