---
# Playbook for managing the database.

- include: pretask.yml

- name: collect info on database connected hosts
  hosts: db_connected
  # NOOP only to acquire IP address information about connected hosts.
  tasks: []

- name: install postgres database
  hosts:
    # FIXME The zclient group's rhaptos site creation requires a local database.
    #       This is only required during provisioning. =/
    - zclient
  roles:
    - postgres
  tags:
    - database
    - legacy_be
    - be

- name: create databases and users
  hosts:
    - database
  roles:
    - cnx_database
  tasks:
    - include: tasks/create_db_user.yml
      vars:
        db_user: "{{ archive_db_user }}"
        db_password: "{{ archive_db_password }}"
    - include: tasks/create_db.yml
      vars:
        db_owner: "{{ archive_db_user }}"
        db_name: "{{ archive_db_name }}"
    - include: tasks/create_db_user.yml
      when: "{{ authoring_db_user is defined }}"
      vars:
        db_user: "{{ authoring_db_user }}"
        db_password: "{{ authoring_db_password }}"
    - include: tasks/create_db_user.yml
      vars:
        db_user: "backups"
        role_attr_flags: ""
    - include: tasks/create_db.yml
      when: "{{ authoring_db_user is defined }}"
      vars:
        db_owner: "{{ authoring_db_user }}"
        db_name: "{{ authoring_db_name }}"
  tags:
    - database
    - be
