---

- name: migrate repository database
  hosts: archive
  tasks:
    - name: stop archive
      become: yes
      supervisorctl:
        name: "archive:"
        state: stopped

    - name: migrate repository database
      become: yes
      become_user: www-data
      environment:
        # If PGHOST is not set, psql tries to look for cluster "main" which doesn't
        # work:
        #     $ psql -U postgres -l
        #     Error: Invalid data directory
        # This appears to be a problem after a postgresql-common update
        PGHOST: "{{ archive_db_host }}"
      command: "/var/cnx/venvs/archive/bin/dbmigrator --config /etc/cnx/archive/app.ini --context cnx-db migrate"

    - name: start archive
      become: yes
      supervisorctl:
        name: "archive:"
        state: started
