---
- name: setup iptables
  hosts: all:!local
  gather_facts: no
  roles:
    - role: iptables
      when:
        - install_iptables is defined
        - install_iptables
      tags:
        - iptables
  tags:
    - iptables
