---
- name: setup of iptables
  hosts: all:!local
  gather_facts: no
  roles:
    - role: iptables
      when:
        - install_firewall is defined
        - install_firewall|bool
      tags:
        - iptables
        - firewall
  tags:
    - iptables
    - firewall
