---
- name: setup iptables
  hosts: all:!local
  gather_facts: no
  roles:
    - role: iptables
      when:
        - install_iptables|bool == true
      tags:
        - iptables
  tags:
    - iptables
