---
# Playbook for installing the HAProxy service for initial request consumption.

- include: pretask.yml

- name: collect info on connected hosts
  hosts:
    - frontend
    - legacy_frontend
  # NOOP only to acquire IP address information about hosts.
  tasks: []

- name: generate a self-signed certificate
  hosts: local
  vars:
    cert_password: "password"
    cert_domain: "*.{{ frontend_domain }}"
    cert_dir: "{{ inventory_dir }}/secrets/certs"
    cert_pem_filepath: "{{ cert_dir }}/{{ frontend_domain }}.pem"
  tasks:
    - file:
        path: "{{ cert_dir }}"
        state: directory
    - stat: path="{{ cert_pem_filepath }}"
      register: pem_file
    - include: tasks/create_self_signed_cert.yml
      when: not pem_file.stat.exists

- name: setup initial request frontend services
  hosts:
    - lead_frontend
  vars:
    cert_domain: "*.{{ frontend_domain }}"
    cert_dir: "{{ inventory_dir }}/secrets/certs"
    cert_pem_filepath: "{{ cert_dir }}/{{ frontend_domain }}.pem"
  roles:
    - lead_load_balancer
