---
# Used to setup a deployment on localhost.

# Note, 'local' (the host name in the inventory)
#   should be assigned ``ansible_connection=local``.

- include: pretask.yml

- name: "notify #cnx-stream of the deployment (start)"
  hosts:
    - archive
    - publishing
    - authoring
    - frontend
    - worker
    - database
    - zeo
    - zclient
    - pdf_gen
  vars:
    msg: "{{ ansible_user_id }} started deploy to {{ inventory_hostname }} :hourglass_flowing_sand:"
    channel: "#cnx-stream"
  tasks:
    - include: tasks/notify_slack.yml

# +++
# Source gathering
# +++

- name: package up source for shipment
  hosts: local
  tasks:
    - include: tasks/checkout.yml
    - include: tasks/archive_source.yml

- name: checkout cnx-buildout
  hosts: local
  vars:
    source:
      - name: cnx-buildout
        repo: git@github.com:Rhaptos/cnx-buildout.git
        default_version: HEAD
  tasks:
    - include: tasks/checkout.yml
    - include: tasks/archive_source.yml

- name: send source to hosts
  hosts:
    - archive
    - publishing
    - authoring
    - worker
    - database
  tasks:
    - include: tasks/plant_source.yml

- name: send cnx-buildout source to hosts
  hosts:
    - zeo
    - zclient
    - pdf_gen
  vars:
    source:
      - name: cnx-buildout
        repo: git@github.com:Rhaptos/cnx-buildout.git
        default_version: HEAD
  tasks:
    - include: tasks/plant_source.yml

# +++
# Install unpackaged dependencies
# +++

- name: build python 2.4
  hosts:
    - zeo
    - zclient
    - pdf_gen
  tasks:
    - stat: path=/usr/local/bin/python2.4
      register: python24_binary
    - include: tasks/install_python24.yml
      when: not python24_binary.stat.exists

# +++
# Persistence services
# +++

- include: nfs.yml
- include: nfs_connected.yml

- name: install postgres database
  hosts:
    - database
    # Only needed on this host(s) for provisioning
    - zeo
    - zclient
    - pdf_gen
  tasks:
    - include: tasks/install_postgres.yml

- name: install postgres extensions
  hosts:
    - database
  tasks:
    - include: tasks/install_plxslt.yml
    - include: tasks/install_session_exec.yml

- name: create postgres database and users
  hosts:
    - database
  tasks:
    - include: tasks/create_db_user.yml
      vars:
        db_user: "{{ archive_db_user }}"
        db_password: "{{ archive_db_password }}"
    - include: tasks/create_db.yml
      vars:
        db_owner: "{{ archive_db_user }}"
        db_name: "{{ archive_db_name }}"
    - include: tasks/create_db_user.yml
      vars:
        db_user: "{{ authoring_db_user }}"
        db_password: "{{ authoring_db_password }}"
    - include: tasks/create_db_user.yml
      vars:
        db_user: "backups"
        role_attr_flags: ""
    - include: tasks/create_db.yml
      vars:
        db_owner: "{{ authoring_db_user }}"
        db_name: "{{ authoring_db_name }}"

- name: install cnxml dtd pkgs
  hosts:
    - database
    - zeo
    - zclient
    - pdf_gen
  tasks:
    - include: tasks/install_cnxml_dtd.yml

- name: install memcached
  hosts:
    - archive
    - publishing
    - authoring
  tasks:
    - include: tasks/install_memcached.yml

# +++
# Applications
# +++

- name: install supervisor
  hosts:
    - archive
    - publishing
    - authoring
    - zeo
    - zclient
    - pdf_gen
  tasks:
    - include: tasks/install_supervisor.yml

- name: install archive
  hosts: archive
  tasks:
    - include: tasks/install_archive.yml

- name: install publishing
  hosts: publishing
  tasks:
    - include: tasks/install_publishing.yml

- name: install authoring
  hosts: authoring
  tasks:
    - include: tasks/install_authoring.yml

- name: configure buildout
  hosts:
    - zeo
    - zclient
    - pdf_gen
  tasks:
    - include: tasks/configure_buildout.yml
  tags:
    - zope

- name: configure zeo
  hosts:
    - zeo
  tasks:
    - include: tasks/configure_zeo.yml
  tags:
    - zope

- name: configure zope client(s)
  hosts:
    - zclient
  tasks:
    - include: tasks/configure_zclient.yml
  tags:
    - zope

- name: configure pdf generation
  hosts:
    - pdf_gen
  tasks:
    - include: tasks/configure_pdf_gen.yml
  tags:
    - zope

- name: install zope
  hosts:
    - zeo
    - zclient
    - pdf_gen
  tasks:
    - include: tasks/install_cnx_buildout.yml
  tags:
    - zope

- name: create rhaptos site
  hosts:
    - zeo
  tasks:
    - include: tasks/create_rhaptos_site.yml
  tags:
    - zope

- include: legacy_frontend.yml
  tags:
    - haproxy
    - varnish
    - legacy_fe
    - fe

- name: install frontend
  hosts:
    - frontend
  roles:
    - varnish
    - webview
  tags:
    - nginx
    - varnish
    - webview
    - fe

- include: lead_frontend.yml
  tags:
    - haproxy
    - lead_fe
    - fe

- name: "notify #cnx-stream of the deployment (end)"
  hosts:
    - archive
    - publishing
    - authoring
    - frontend
    - worker
    - database
    - zeo
    - zclient
    - pdf_gen
  vars:
    msg: "Deploy to {{ inventory_hostname }} by {{ ansible_user_id }} was successful :heavy_check_mark:"
    channel: "#cnx-stream"
  tasks:
    - include: tasks/notify_slack.yml
