---
# Used to setup a deployment on localhost.

- import_playbook: pretask.yml

- name: "notify #cnx-stream of the deployment (start)"
  hosts: all
  vars:
    msg: "{{ ansible_user_id }} started deploy to {{ inventory_hostname }} :hourglass_flowing_sand:"
    channels:
      - "#cnx-stream"
      - "#deployments"
  tasks:
    - import_tasks: tasks/notify_slack.yml

# +++
# Persistence services
# +++

- import_playbook: nfs.yml
- import_playbook: nfs_connected.yml

- import_playbook: database.yml
- import_playbook: broker.yml

# +++
# Applications
# +++

- import_playbook: archive.yml not_standalone=yes
- import_playbook: publishing.yml not_standalone=yes
- import_playbook: channel_processing.yml
- import_playbook: publishing_worker.yml
- import_playbook: authoring.yml
- import_playbook: press.yml

- import_playbook: zope.yml not_standalone=yes
  tags:
    - zope
    - zeo
    - zclient
    - pdf_gen
    - legacy_be
    - be

- import_playbook: legacy_frontend.yml
  tags:
    - haproxy
    - varnish
    - legacy_fe
    - fe

- import_playbook: frontend.yml not_standalone=yes
  tags:
    - nginx
    - varnish
    - webview
    - fe

- import_playbook: lead_frontend.yml
  tags:
    - haproxy
    - lead_fe
    - fe

- import_playbook: iptables.yml
  tags:
    - iptables
    - firewall

- import_playbook: sysstat.yml
  tags:
    - sysstat

- import_playbook: update_versions.yml

- import_playbook: run_deferred_migrations.yml

- name: "notify #cnx-stream of the deployment (end)"
  hosts: all
  vars:
    msg: "Deploy to {{ inventory_hostname }} by {{ ansible_user_id }} was successful :heavy_check_mark:"
    channels:
      - "#cnx-stream"
      - "#deployments"
  tasks:
    - import_tasks: tasks/notify_slack.yml
