---
# Used to setup a deployment on localhost.

- include: pretask.yml

- name: "notify #cnx-stream of the deployment (start)"
  hosts: all
  vars:
    msg: "{{ ansible_user_id }} started deploy to {{ inventory_hostname }} :hourglass_flowing_sand:"
    channels:
      - "#cnx-stream"
      - "#deployments"
  tasks:
    - include: tasks/notify_slack.yml

# +++
# Persistence services
# +++

- include: nfs.yml
- include: nfs_connected.yml

- include: database.yml
- include: broker.yml

- name: install cnxml dtd pkgs
  hosts:
    - database
    - replicant
    - zeo
    - zclient
    - pdf_gen
  tasks:
    - include: tasks/install_cnxml_dtd.yml
  tags:
    - install-cnxml-dtd-pkgs

# +++
# Applications
# +++

- include: archive.yml
- include: publishing.yml
- include: channel_processing.yml
- include: publishing_worker.yml
- include: authoring.yml

- include: zope.yml
  tags:
    - zope
    - zeo
    - zclient
    - pdf_gen
    - legacy_be
    - be

- include: legacy_frontend.yml
  tags:
    - haproxy
    - varnish
    - legacy_fe
    - fe

- include: frontend.yml
  tags:
    - nginx
    - varnish
    - webview
    - fe

- include: lead_frontend.yml
  tags:
    - haproxy
    - lead_fe
    - fe

- include: iptables.yml
  tags:
    - iptables
    - firewall

- name: "notify #cnx-stream of the deployment (end)"
  hosts: all
  vars:
    msg: "Deploy to {{ inventory_hostname }} by {{ ansible_user_id }} was successful :heavy_check_mark:"
    channels:
      - "#cnx-stream"
      - "#deployments"
  tasks:
    - include: tasks/notify_slack.yml
