---
# Used to setup a deployment on localhost.

# Note, 'local' (the host name in the inventory)
#   should be assigned ``ansible_connection=local``.

- include: pretask.yml

- name: "notify #cnx-stream of the deployment (start)"
  hosts:
    - nfs
    - database
    - archive
    - publishing
    - authoring
    - lead_frontend
    - legacy_frontend
    - frontend
    - worker
    - zeo
    - zclient
    - pdf_gen
  vars:
    msg: "{{ ansible_user_id }} started deploy to {{ inventory_hostname }} :hourglass_flowing_sand:"
    channels:
      - "#cnx-stream"
      - "#deployments"
  tasks:
    - include: tasks/notify_slack.yml

# +++
# Source gathering
# +++

- name: package up source for shipment
  hosts: local
  tasks:
    - include: tasks/checkout.yml
    - include: tasks/archive_source.yml

- name: send source to hosts
  hosts:
    - archive
    - publishing
    - authoring
    - worker
    - database
  tasks:
    - include: tasks/plant_source.yml

# +++
# Persistence services
# +++

- include: nfs.yml
- include: nfs_connected.yml

- include: database.yml

- name: install cnxml dtd pkgs
  hosts:
    - database
    - zeo
    - zclient
    - pdf_gen
  tasks:
    - include: tasks/install_cnxml_dtd.yml

- name: install memcached
  hosts:
    - archive
    - publishing
    - authoring
  roles:
    - memcached
  tags:
    - memcached
    - be

# +++
# Applications
# +++

- name: install supervisor
  hosts:
    - archive
    - publishing
    - authoring
    - zeo
    - zclient
    - pdf_gen
  tasks:
    - include: tasks/install_supervisor.yml

- name: install archive
  hosts: archive
  tasks:
    - include: tasks/install_archive.yml

- name: install publishing
  hosts: publishing
  tasks:
    - include: tasks/install_publishing.yml

- name: install authoring
  hosts: authoring
  tasks:
    - include: tasks/install_authoring.yml

- include: zope.yml
  tags:
    - zope
    - zeo
    - zclient
    - pdf_gen
    - legacy_be
    - be

- include: legacy_frontend.yml
  tags:
    - haproxy
    - varnish
    - legacy_fe
    - fe

- include: frontend.yml
  tags:
    - nginx
    - varnish
    - webview
    - fe

- include: lead_frontend.yml
  tags:
    - haproxy
    - lead_fe
    - fe

- name: "notify #cnx-stream of the deployment (end)"
  hosts:
    - nfs
    - database
    - archive
    - publishing
    - authoring
    - lead_frontend
    - legacy_frontend
    - frontend
    - worker
    - zeo
    - zclient
    - pdf_gen
  vars:
    msg: "Deploy to {{ inventory_hostname }} by {{ ansible_user_id }} was successful :heavy_check_mark:"
    channels:
      - "#cnx-stream"
      - "#deployments"
  tasks:
    - include: tasks/notify_slack.yml
