---
# Creates a self-signed certificate.
# The certificate key is signed with ``cert_password``,
# this property is required for the creation of the certificate.
# However, the resulting certificate key file will be unencrypted for convenience.

# Properties:
#  - cert_password: used when creating the certificate signing key
#  - cert_domain: a string for the domain (e.g. example.com)
#  - cert_crt_filepath: where to put the created crt file
#  - cert_key_filepath: where to put the created signing key file

- file:
    path: tmp
    state: directory

- name: generate a private key
  command: "openssl genrsa -des3 -out server.key -passout pass:{{ cert_password }} 1024"
  args:
    chdir: tmp

- name: generate a csr
  command: "openssl req -new -key server.key -out server.csr -passin pass:{{ cert_password }} -subj '/countryName=US/stateOrProvinceName=TX/localityName=Houston/organizationName=OpenStax/commonName={{ cert_domain }}/'"
  args:
    chdir: tmp

- copy:
    src: tmp/server.key
    dest: tmp/server.key.orig

- name: remove passphrase from key
  command: "openssl rsa -in server.key.orig -out server.key -passin pass:{{ cert_password }}"
  args:
    chdir: tmp

- name: generate a self-signed certificate
  command: "openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt"
  args:
    chdir: tmp

- name: create the .pem file
  shell: "cat tmp/server.crt tmp/server.key | tee {{ cert_pem_filepath }}"
