---
# Create a postgresql database user with superuser privileges.

# Installed for the postgresql_* ansible modules.
- become: yes
  apt:
    name: python-psycopg2
    state: present

- name: create the db user
  become: yes
  become_user: postgres
  postgresql_user:
    db: postgres
    login_host: "{{ db_host|default('localhost') }}"
    port: "{{ db_port|default(5432) }}"
    login_user: postgres
    name: "{{ db_user }}"
    password: "{{ db_password|default('') }}"
    role_attr_flags: "{{ role_attr_flags|default('CREATEDB,NOSUPERUSER') }}"
  tags:
    - create-db-user
