---
# Notify a slack channel with a message

- name: notify slack
  when: "slack_token is defined"
  local_action:
    module: slack
    token: "{{ slack_token }}"
    msg: "{{ msg }}"
    channel: "{{ item }}"
    username: "Ansible on {{ inventory_hostname }}"
    link_names: 0
    parse: 'none'
  with_items: "{{ channels }}"
  run_once: true
  tags:
    - notify
    - slack
