---
root_prefix: ""
_host_prefix: easyvm5

archive_db_name: "{{ vault_archive_db_name }}"
archive_db_user: "{{ vault_archive_db_user }}"
archive_db_password: "{{ vault_archive_db_password }}"
archive_db_host: "{{ _host_prefix }}.cnx.org"
archive_db_port: 5432
archive_pserve_path: /var/cnx/venvs/python2/archive/bin/pserve


publishing_broker_user: cnxpublishing
publishing_broker_password: cnxpublishing

authoring_db_name: "{{ vault_authoring_db_name }}"
authoring_db_user: "{{ vault_authoring_db_user }}"
authoring_db_password: "{{ vault_authoring_db_password }}"
authoring_db_host: "{{ _host_prefix }}.cnx.org"
authoring_db_port: 5432

press_db_name: "{{ archive_db_name }}"
press_db_user: "{{ archive_db_user }}"
press_db_password: "{{ archive_db_password }}"
press_db_host: "{{ archive_db_host }}"
press_db_port: "{{ archive_db_port }}"
press_broker_user: press
press_broker_password: press

sentry_dsn: "{{ vault_sentry_dsn }}"

# FIXME Not really yaml'ish to use space separated values...
# Note, don't confuse the usage of 'hosts' here with ansible 'hosts'.
# 'hosts' is a space separated value containing hostnames or ip addresses
# where a memcached instance is running.
memcached_hosts: localhost

varnish_port: 8990
legacy_varnish_port: 8991
haproxy_zcluster_port: 8998

archive_host: "{{ _host_prefix }}.cnx.org"
publishing_host: "{{ _host_prefix }}.cnx.org"
authoring_host: "{{ _host_prefix }}.cnx.org"
zclient_base_port: 8280
zclient_count: 1

zope_domain: "legacy-{{ _host_prefix }}.cnx.org"
arclishing_domain: "archive-{{ _host_prefix }}.cnx.org"
frontend_domain: "{{ _host_prefix }}.cnx.org"
accounts_domain: accounts-qa1.openstax.org
tutor_domain: tutor-qa.openstax.org
exercises_domain: exercises.openstax.org
cms_domain: openstax.org

accounts_disable_verify_ssl: yes
accounts_stub: yes

accounts_consumer_token: "{{ vault_accounts_consumer_token }}"
accounts_consumer_secret: "{{ vault_accounts_consumer_secret }}"

exercises_token: "{{ vault_exercises_token }}"

postgres_connections: "{{ vault_postgres_connections }}"

slack_token: "{{ vault_slack_token }}"

nfs_server_for_files1: "{{ _host_prefix }}.cnx.org"
nfs_server_for_files2: "{{ _host_prefix }}.cnx.org"
nfs_server_for_specials: "{{ _host_prefix }}.cnx.org"

webview_version: master

princexml_deb_url: "http://www.princexml.com/download/prince_11-1_ubuntu16.04_amd64.deb"
rex_domain: staging.openstax.org
rex_redirects_enabled: false
