---

# +++
# Install
# +++

- name: install supervisor
  become: yes
  apt:
    name: supervisor
    state: present

# +++
# Initialize
# +++

- stat: path="{{ root_prefix }}/etc/supervisor/supervisord.conf"
  register: supervisord_conf

- name: create supervisord.conf
  when: not supervisord_conf.stat.exists
  shell: echo_supervisord_conf > "/etc/supervisor/supervisord.conf"

- name: "ensure /etc/supervisor/conf.d exists"
  file:
    path: "/etc/supervisor/conf.d"
    state: directory

# +++
# Configure
# +++

- name: configure supervisor include section
  become: yes
  lineinfile:
    dest: "/etc/supervisor/supervisord.conf"
    regexp: "^\\[include\\]$"
    line: "[include]"
    insertafter: EOF
    state: present
  notify:
    - restart supervisord

- name: configure supervisor include files path
  become: yes
  lineinfile:
    dest: "/etc/supervisor/supervisord.conf"
    regexp: "^files = [\\w/]+etc/supervisor/conf.d/\\*(.conf)?$"
    line: "files = /etc/supervisor/conf.d/*.conf"
    insertafter: "^\\[include\\]$"
    state: present
  notify:
    - restart supervisord

# +++
# Init services
# +++

- name: start supervisor
  become: yes
  service:
    name: supervisor
    state: started
