# based on https://github.com/lesovsky/ansible-postgresql-sr-on-el6

- name: stop postgresql on replicant
  service:
    name: postgresql
    state: stopped

- name: remove old postgresql cluster on replicant
  file:
    path: XXX
    state: absent

# pg_basebackup

- name: configure recovery.conf
  template:
    src: XXX/recovery.conf
    dest: "{{ postgresql_data_dir }}/recovery.conf"
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0640

- name: start postgresql service
  service:
    name: postgresql
    state: started
    enabled: yes
