---
- import_tasks: zabbix-agent.yml
  tags:
    - zabbix
    - zabbix-agent
    - config

- name: notify handler
  command: 'true'
  notify: zabbix-agent
  when: notify_all_handlers
  tags:
    - zabbix
    - zabbix-agent
    - handler
