---
- name: install or upgrade apt package
  apt:
    name: zabbix-agent
    state: latest
  notify: zabbix-agent

- name: install or update pip package
  pip:
    name: zabbix-api
    state: latest
  notify: zabbix-agent

- name: register host on Zabbix server
  zabbix_host:
    server_url: https://monitor.openstax.org
    login_user: "{{ zabbix_admin_user }}"
    login_password: "{{ zabbix_admin_password }}"
    host_name: "{{ zabbix_agent_config_hostname }}"
    link_templates:
      - "Template SSH Service"
      - "Template Ubuntu Config"
      - "Template Ubuntu Load"
      - "Template Server Security"
    timeout: 30
    interfaces:
      - type: 1
        main: 1
        useip: 0
        ip: ""
        dns: "{{ zabbix_agent_config_hostname }}"
        port: 10051
  notify: zabbix-agent

- name: ensure log symlink exists
  file:
    src: /var/log/zabbix-agent
    dest: /var/log/zabbix
    owner: "{{ zabbix_agent_user }}"
    group: "{{ zabbix_agent_group }}"
    state: link
    force: True
  notify: zabbix-agent

- name: install configuration and set permissions
  template:
    src: root/etc/zabbix/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: "{{ zabbix_agent_user }}"
    group: "{{ zabbix_agent_group }}"
    mode: 0640
  notify: zabbix-agent
