---

- name: list supervisor applications
  become: yes
  command: supervisorctl avail
  register: supervisorctl_avail

- name: restart press
  become: yes
  supervisorctl:
    name: "press:"
    state: restarted
  when: supervisorctl_avail.stdout.find('press') != -1

- name: restart press workers
  become: yes
  supervisorctl:
    name: "press_worker:"
    state: restarted
  when: supervisorctl_avail.stdout.find('press_worker:') != -1
