---

- name: list supervisor applications
  become: yes
  command: supervisorctl avail
  register: supervisorctl_avail
  listen: restart press

- name: restart press
  become: yes
  supervisorctl:
    name: "press:"
    state: restarted
  when: supervisorctl_avail.stdout.find('press') != -1
