---
# Adds the Postgres repository to the system

- name: remove old pgdg repository
  become: yes
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.3"
    filename: pgdg
    state: absent
    update_cache: yes

- name: add apt-key for pgdg repository
  become: yes
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add pgdg repository
  become: yes
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    update_cache: yes
