---
varnish:
  user: varnishlog
  group: varnish
  port: "{{ varnish_port|default(80) }}"
  malloc: "{{ varnish_malloc|default('16g') }}"
  templates:
    - {src: varnishncsa.format, dest: /var/log/varnish/varnishncsa.format, user: varnishlog, group: varnish}
    - {src: lib/systemd/system/varnish.service, dest: /etc/systemd/system/multi-user.target.wants/varnish.service}
    - {src: lib/systemd/system/varnishncsa.service, dest: /etc/systemd/system/multi-user.target.wants/varnishncsa.service}
    - {src: lib/systemd/system/varnishlog.service, dest: /etc/systemd/system/multi-user.target.wants/varnishlog.service}
    - {src: etc/default/varnish, dest: /etc/default/varnish}
    - {src: etc/default/varnishncsa, dest: /etc/default/varnishncsa}
    - {src: etc/default/varnishlog, dest: /etc/default/varnishlog}
