---
# Install and configure RabbitMQ
# See also https://www.rabbitmq.com/install-debian.html

- name: install rabbitmq
  become: yes
  apt:
    name: rabbitmq-server
    state: present

# Install plugins

- name: enable rabbitmq management plugin
  become: yes
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
