---
# Configure buildout for use with ansible

# Create an include buildout file that we can modify to include other ansible
# generated buildout configuration.

- name: configure buildout for ansible
  become: yes
  template:
    src: var/lib/cnx/cnx-buildout/ansible.cfg
    dest: "/var/lib/cnx/cnx-buildout/ansible.cfg"
    owner: www-data
    group: www-data
    mode: '0640'
  vars:
    dist_cnx_username: >-
     {{ lookup('aws_secret', dist_cnx_username_secret, region=aws_secrets_region)
         if (lookup('env', 'AWS_ACCESS_KEY_ID') or lookup('env', 'AWS_PROFILE'))
         else dist_cnx_dev_username|default('') }}
    dist_cnx_password: >-
      {{ lookup('aws_secret', dist_cnx_password_secret, region=aws_secrets_region)
         if (lookup('env', 'AWS_ACCESS_KEY_ID') or lookup('env', 'AWS_PROFILE'))
         else dist_cnx_dev_password|default('') }}

- name: place the ansible-versions.cfg
  become: yes
  copy:
    src: "{{ inventory_dir }}/files/versions.cfg"
    dest: "/var/lib/cnx/cnx-buildout/ansible-versions.cfg"
    owner: www-data
    group: www-data
