---
# Configure Zope client instances

# The buildout already contains a section to create an instance.
# Here want to configure and create several instance configurations.

# This gets included in the buildout via the configure_buildout.yml task.
- name: configure frontend(s)
  become: yes
  template:
    src: var/lib/cnx/cnx-buildout/ansible-zclients.cfg
    dest: "/var/lib/cnx/cnx-buildout/ansible-zclients.cfg"
    owner: www-data
    group: www-data
    mode: 0644
