---
# Configure buildout for use with ansible

# Create an include buildout file that we can modify to include other ansible
# generated buildout configuration.

- name: configure buildout for ansible
  become: yes
  template:
    src: var/lib/cnx/cnx-buildout/ansible.cfg
    dest: "/var/lib/cnx/cnx-buildout/ansible.cfg"
    owner: www-data
    group: www-data

- name: place the ansible-versions.cfg
  become: yes
  copy:
    src: "{{ inventory_dir }}/files/versions.cfg"
    dest: "/var/lib/cnx/cnx-buildout/ansible-versions.cfg"
    owner: www-data
    group: www-data
