---
# Installs cnx zope instance with all the dependencies.

# +++
# Prerequisites
# +++

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - openjdk-8-jre-headless
    - libjpeg-dev
    - libpng-dev
    - build-essential
    # lxml dependencies
    - libxml2-dev
    - libxslt1-dev
  tags: buildout-apt

# +++
# Install virtualenv
# +++

- name: ensure the venvs directory exists
  become: yes
  file:
    path: "/var/cnx/venvs"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  tags: buildout-venvs

- shell: which python2.4
  register: python24_path

# virtualenv 1.7.2 is the last known version to work with Python 2.4.
- name: download virtualenv 1.7.2 (for python 2.4)
  unarchive:
    src: https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.7.2.tar.gz#md5=b5d63b05373a4344ae099a68875aae78
    dest: .
    copy: no

- name: create the cnx-buildout virtualenv
  become: yes
  shell: "{{ python24_path.stdout }} virtualenv-1.7.2/virtualenv.py /var/cnx/venvs/cnx-buildout"

- name: delete virtualenv 1.7.2 source code
  file:
    path: virtualenv-1.7.2
    state: absent

# +++
# Install cnx-buildout
# +++

- name: copy cached python packages downloads directory
  become: yes
  synchronize:
    src: src/cnx-buildout/downloads
    dest: "/var/lib/cnx/cnx-buildout"
    owner: no
    group: no
  tags: buildout-copy

- name: ensure proper ownership of buildout
  become: yes
  file:
    path: /var/lib/cnx/cnx-buildout
    recurse: yes
    state: directory
    owner: www-data
    group: www-data
  tags: buildout-perms

- name: run bootstrap
  become: yes
  become_user: www-data
  shell: "/var/cnx/venvs/cnx-buildout/bin/python bootstrap.py"
  args:
    chdir: "/var/lib/cnx/cnx-buildout"
  tags: buildout-bootstrap

- name: install simplejson 1.9.2
  become: yes
  pip:
    name: simplejson
    version: 1.9.2
    virtualenv: "/var/cnx/venvs/cnx-buildout"
    virtualenv_python: python2

- name: run buildout
  become: yes
  shell: ". /var/cnx/venvs/cnx-buildout/bin/activate && bin/buildout -c ansible.cfg -vvvv 2>&1 | tee buildout_output.txt"
  args:
    chdir: "/var/lib/cnx/cnx-buildout"

- name: install lxml 3.2.1
  become: yes
  shell: ". bin/libs.sh && /var/cnx/venvs/cnx-buildout/bin/pip install lxml==3.2.1"
  args:
    chdir: "/var/lib/cnx/cnx-buildout"

- name: install python-memcached and hashlib
  become: yes
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: pip-2.4
  with_items:
    - name: python-memcached
      version: 1.48
    - name: hashlib
      version: 20081119

- name: ensure /var/www/files directory exists
  become: yes
  file:
    path: "/var/www/files"
    state: directory
    owner: www-data
    group: www-data

- name: assign permissions group
  become: yes
  file:
    path: "/var/lib/cnx/cnx-buildout"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
