---
# Installs publishing with all the dependencies.

# +++
# Init service
# +++

- name: configure publishing celery workers under supervisor
  become: yes
  template:
    src: etc/supervisor/conf.d/publishing_celery_workers.conf
    dest: "/etc/supervisor/conf.d/publishing_celery_workers.conf"
    mode: 0644
  notify:
    - reload supervisord
