---
# Installs publishing with all the dependencies.

# +++
# Init service
# +++

- name: configure publishing celery workers under supervisor
  become: yes
  template:
    src: etc/supervisor/conf.d/publishing_celery_workers.conf
    dest: "/etc/supervisor/conf.d/publishing_celery_workers.conf"
    mode: 0644
  notify:
    - reload supervisord

# +++
# Rsyslog Configuration
# +++

- name: connect publishing worker log to rsyslog
  become: yes
  template:
    src: "etc/rsyslog.d/10-publishing-worker.conf"
    dest: "/etc/rsyslog.d/10-publishing-worker.conf"
    mode: 0644
  notify:
    - set up supervisor logs
    - restart rsyslog
  tags:
    - publishing-worker-rsyslog
