---

# +++
# Install
# +++

- name: install exim4
  become: yes
  apt:
    name: exim4
    state: present
  tags:
    - mail

# +++
# Configure
# +++

- name: set mailname
  become: yes
  copy:
    content: "{{ inventory_hostname }}\n"
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify: restart exim4
  tags:
    - mail

- name: configure exim4
  become: yes
  template:
    src: etc/exim4/update-exim4.conf.conf
    dest: /etc/exim4/update-exim4.conf.conf
    mode: 0644
  notify: restart exim4
  tags:
    - mail

