---

- name: restart supervisord
  become: yes
  service:
    name: supervisor
    state: restarted
  register: restart_supervisor_handler
  notify:
    - set up supervisor logs

- name: reload supervisord
  when: restart_supervisor_handler is undefined
  become: yes
  service:
    name: supervisor
    state: reloaded
  notify:
    - set up supervisor logs

- name: set up supervisor logs
  become: yes
  shell: "chmod 644 /var/log/supervisor/*"
