---

- name: restart supervisord
  become: yes
  service:
    name: supervisor
    state: restarted
  register: restart_supervisor_handler

- name: reload supervisord
  when: restart_supervisor_handler is undefined
  become: yes
  service:
    name: supervisor
    state: reloaded
