---

- name: restart daemon tools
  become: yes
  # This makes our service file changes available for use.
  shell: systemctl daemon-reload

- name: enable legacy-varnishlog
  become: yes
  # Usually we would do "systemctl enable varnishlog", but it is failing:
  # Synchronizing state of varnishlog.service with SysV init with /lib/systemd/systemd-sysv-install...
  # Executing /lib/systemd/systemd-sysv-install enable varnishlog
  # Failed to execute operation: Invalid argument
  file:
    src: "/etc/systemd/system/legacy-varnishlog.service"
    dest: "/etc/systemd/system/multi-user.target.wants/legacy-varnishlog.service"
    state: link
    force: yes

- name: enable legacy-varnishncsa
  become: yes
  file:
    src: "/etc/systemd/system/legacy-varnishncsa.service"
    dest: "/etc/systemd/system/multi-user.target.wants/legacy-varnishncsa.service"
    state: link
    force: yes

- name: enable legacy-varnish
  become: yes
  file:
    src: "/etc/systemd/system/legacy-varnish.service"
    dest: "/etc/systemd/system/multi-user.target.wants/legacy-varnish.service"
    state: link
    force: yes

- name: start legacy-varnishlog
  become: yes
  service:
    name: legacy-varnishlog
    state: started

- name: start legacy-varnishncsa
  become: yes
  service:
    name: legacy-varnishncsa
    state: started

- name: restart legacy-varnish
  become: yes
  service:
    name: legacy-varnish
    state: restarted
  register: restart_legacy_varnish_handler

- name: reload legacy-varnish
  when: restart_legacy_varnish_handler is undefined
  become: yes
  service:
    name: legacy-varnish
    state: reloaded
