---

# +++
# Init service
# +++

- name: configure press under supervisor
  become: yes
  template:
    src: etc/supervisor/conf.d/press.conf
    dest: "/etc/supervisor/conf.d/press.conf"
    mode: 0644
  notify:
    - reload supervisord
