---
# Installs Press

# +++
# Prerequisites
# +++

- name: install system level dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - git
    - libpq-dev
    - libxml2-dev
    - libxslt-dev
    - zlib1g-dev

- name: install postgres client
  become: yes
  apt:
    name: "postgresql-client-{{ postgres_version }}"
    state: present

# +++
# Install virtualenv(s)
# +++

- stat:
    path: "/var/cnx/venvs"
  register: venvs_dir

- name: ensure the venvs directory exists
  become: yes
  when: not venvs_dir.stat.exists
  file:
    path: "/var/cnx/venvs"
    state: directory
    mode: 0755
    owner: www-data

- name: set the owner of venvs directory
  become: yes
  file:
    path: "/var/cnx/venvs"
    state: directory
    recurse: yes
    owner: www-data

- name: create the venv
  become: yes
  become_user: www-data
  command: "python3 -m venv /var/cnx/venvs/press"

# +++
# Install
# +++

- stat:
    path: "/var/cnx/apps"
  register: apps_dir

- name: ensure the apps directory exists
  become: yes
  when: not apps_dir.stat.exists
  file:
    path: "/var/cnx/apps"
    state: directory
    mode: 0755
    owner: www-data

- name: set the owner of apps directory
  become: yes
  file:
    path: "/var/cnx/apps"
    state: directory
    recurse: yes
    owner: www-data

- name: checkout codebase
  become: yes
  become_user: www-data
  git:
    repo: "https://github.com/Connexions/cnx-press.git"
    dest: "/var/cnx/apps/press"
    version: "{{ press_version|default('HEAD') }}"

- name: install dependencies
  become: yes
  become_user: www-data
  pip:
    virtualenv: "/var/cnx/venvs/press"
    requirements: "/var/cnx/apps/press/requirements/{{ item }}"
  with_items:
    - "main.txt"
    - "deploy.txt"

# +++
# Configure
# +++

- name: ensure the etc directories exists
  become: yes
  file:
    path: "/etc/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - cnx
    - cnx/press

- name: render configuration
  become: yes
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - "etc/cnx/press/vars.sh"
  notify:
    - list supervisor applications
    - restart press

# +++
# Init service
# +++

- name: configure press under supervisor
  become: yes
  template:
    src: etc/supervisor/conf.d/press.conf
    dest: "/etc/supervisor/conf.d/press.conf"
    mode: 0644
  notify:
    - reload supervisord
