#!/bin/bash
#exec 1>> /tmp/archive-restart.$$.stdout
#exec 2>> /tmp/archive-restart.$$.stderr

#set -vx

idle_before=$(psql -U rhaptos repository -tA -c "SELECT COUNT(*) FROM pg_stat_activity WHERE (state = 'idle');")

while read -r instance status _
do
    if [[ $status == RUNNING || $status == STOPPED ]]
    then
        sudo supervisorctl restart "$instance"
        sleep 2
    fi
done < <(sudo supervisorctl status 'archive:*')

(( idle_after = idle_before ))
(( tries = 0 ))

while (( idle_after >= idle_before && ++tries <= 10 ))
do
    sleep 60
    idle_after=$(psql -U rhaptos repository -tA -c "SELECT COUNT(*) FROM pg_stat_activity WHERE (state = 'idle');")
#    echo "$(date) Try $tries, Before $idle_before, After $idle_after" >&2
done

logger -p local0.notice -t "ARCHIVE-RESTART[$$]" "Postgresql idle connections before restart: $idle_before, after: $idle_after"
