#!/bin/bash
#exec 1>> /tmp/archive-restart.$$.stdout
#exec 2>> /tmp/archive-restart.$$.stderr

#set -vx

restart_threshold=30

source /etc/cnx/archive/vars.sh

db_host=$archive_db_host
db_port=$archive_db_port
db_name=$archive_db_name
db_user=$archive_db_user

idle_before=$(psql -h "$db_host" -p "$db_port" -U "$db_user" "$db_name" -tA -c "SELECT COUNT(*) FROM pg_stat_activity WHERE (state = 'idle');")

idle_after=$idle_before
tries=0

if (( idle_before > restart_threshold ))
then
    while read -r instance status _
    do
        if [[ $status == RUNNING || $status == STOPPED ]]
        then
            sudo supervisorctl restart "$instance"
            sleep 10
        fi
    done < <(sudo supervisorctl status 'archive:*')

    while (( idle_after >= idle_before && ++tries <= 10 ))
    do
        sleep 60
        idle_after=$(psql -h "$db_host" -p "$db_port" -U "$db_user" "$db_name" -tA -c "SELECT COUNT(*) FROM pg_stat_activity WHERE (state = 'idle');")
    #    echo "$(date) Try $tries, Before $idle_before, After $idle_after" >&2
    done
fi

logger -p local0.notice -t "ARCHIVE-RESTART[$$]" "Postgresql idle connections to $db_host - before restart: $idle_before, after: $idle_after"
