---
# Install Python 3.x

- name: add deadsnakes ppa
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'

- name: install python 3.6
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "python3.6-dev"
    - "python3.6-venv"
