---
# Installs press with all the dependencies.

# +++
# Init service
# +++

- name: configure press celery workers under supervisor
  become: yes
  template:
    src: etc/supervisor/conf.d/press_celery_workers.conf
    dest: "/etc/supervisor/conf.d/press_celery_workers.conf"
    mode: 0644
  notify:
    - reload supervisord
  register: press_worker_supervisor_conf

# When state = present module calls reread and then add
- name: add supervisor config
  become: yes
  supervisorctl:
    name: "press_worker:"
    state: present
  when: press_worker_supervisor_conf.changed

# When state = restarted module calls update and then restart
- name: add supervisor config
  become: yes
  supervisorctl:
    name: "press_worker:"
    state: restarted
  when: press_worker_supervisor_conf.changed

# +++
# Rsyslog Configuration
# +++

- name: connect press worker log to rsyslog
  become: yes
  template:
    src: "etc/rsyslog.d/10-press-worker.conf"
    dest: "/etc/rsyslog.d/10-press-worker.conf"
    mode: 0644
  notify:
    - set up supervisor logs
    - restart rsyslog
  tags:
    - press-worker-rsyslog
