---

- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted

- name: restart haproxy
  become: yes
  service:
    name: haproxy
    state: restarted
  register: restart_haproxy_handler

- name: reload haproxy
  when: restart_haproxy_handler is undefined
  become: yes
  service:
    name: haproxy
    state: reloaded
