#!/bin/bash
#set -e

log_root={{ varnish_logroot|default('/var/www/varnish_logs') }}
log_user={{ varnish_user|default('varnishlog') }}
log_group={{ varnish_group|default('varnish') }}
combined_out="${log_root}/varnishncsa_combined.log"
current_datestamp=$(date -d "$(printf '%(%m/%d/%Y)T 00:00:00')" +%s)
timestamp_file="${log_root}/varnish_last_import"
varnfiles_tmp=$(mktemp /tmp/varnish.XXXXXX)

# Run find command to create a temp file to use for combining logs
# into one file.
# If you are wondering why +20c it's because an empty gz file is 20 bytes
if [[ ! -e $timestamp_file ]] ; then
    find ${log_root}/ -mindepth 1 \( \
        -name varnishncsa.log.\*.gz -size +20c \
    \) -fprintf $varnfiles_tmp '%p\0'
else
    read -r -d '' import_time < $timestamp_file
    # Or use
    # import_time=$(date -r $timestamp_file +%s)
    find ${log_root}/ -mindepth 1 \( \
        -name varnishncsa.log.\*.gz -size +20c -newermt "@${import_time}" \
    \) -fprintf $varnfiles_tmp '%p\0'
fi

# If the temporary file is not empty
if [[ -s $varnfiles_tmp ]] ; then
    xargs -0 -a $varnfiles_tmp zcat > $combined_out
    /var/cnx/venvs/archive/bin/cnx-archive-hits_counter \
        --hostname={{ arclishing_domain }} --log-format=plain \
        /etc/cnx/archive/app.ini $combined_out
    printf $current_datestamp > $timestamp_file
    touch -d "@${current_datestamp}" $timestamp_file
    chown ${log_user}.${log_group} $combined_out $timestamp_file
fi

# Remove the temporary file regardless of whether it was used or not
/bin/rm -f $varnfiles_tmp
