---
# Configures SSL sites for cnx sites.

- name: install certificate pem
  become: yes
  copy:
    src: "{{ cert_pem_filepath }}"
    dest: "{{ root_prefix }}/etc/ssl/certs/{{ frontend_domain }}.pem"
    owner: "{{ cert_owner|default('root') }}"
    group: "{{ cert_group|default('root') }}"
    mode: 0600
  notify: "{{ on_ssl_install }}"
