---
# Configure PDF Generation

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - python-imaging
    - gif2png
    - cjk-latex
    - texlive-latex-extra
    - xsltproc
    - xvfb
    - xfonts-base
    - libreoffice
    - imagemagick
    - tralics
    - unzip
    - libxml2-utils
    - texlive-latex3
    - libedit-dev
    - zip
    - libreoffice-script-provider-python
    - ruby
    - inkscape
    - docbook-xsl-ns
    - texlive-fonts-recommended
    - memcached
    - librsvg2-bin
    - otf-stix
    - openjdk-8-jdk
    - jpegoptim

- name: install princexml
  apt:
    deb: "{{ princexml_deb_url }}"
  become: yes

- name: stat princexml license file
  local_action:
    module: stat
    path: "{{ princexml_license_filepath }}"
  register: princexml_license_stat
  tags:
    - install-princexml-license

- name: install princexml license file
  when: "princexml_license_stat.stat.exists"
  become: yes
  copy:
    src: "{{ princexml_license_filepath }}"
    dest: "/usr/lib/prince/license/license.dat"
    mode: 0744
  tags:
    - install-princexml-license

- name: create directory for urw fonts
  become: yes
  file:
    path: "/usr/share/fonts/urw"
    state: directory
    mode: 0755

- name: download urw fonts
  become: yes
  get_url:
    url: "http://svn.ghostscript.com/ghostscript/trunk/ghostpdl/urwfonts/{{ item }}"
    dest: "/usr/share/fonts/urw"
  with_items:
    - URWPalladioL-Bold.ttf
    - URWPalladioL-BoldItal.ttf
    - URWPalladioL-Ital.ttf
    - URWPalladioL-Roma.ttf

- name: configure pdf_gen in supervisor
  become: yes
  template:
    src: etc/supervisor/conf.d/pdf_gen.conf
    dest: "/etc/supervisor/conf.d/pdf_gen.conf"
    mode: 0644
  register: supervisor_conf_for_pdf_gen
  notify:
    - reload supervisord

- name: restart pdf_gen
  when: "{{ not supervisor_conf_for_pdf_gen|changed }}"
  become: yes
  supervisorctl:
    name: pdf_gen
    state: restarted
