---
# Configure PDF Generation

- name: configure pdf_gen in supervisor
  become: yes
  template:
    src: etc/supervisor/conf.d/pdf_gen.conf
    dest: "/etc/supervisor/conf.d/pdf_gen.conf"
    mode: 0644
  register: supervisor_conf_for_pdf_gen
  notify:
    - reload supervisord

- name: restart pdf_gen
  when: not supervisor_conf_for_pdf_gen|changed
  become: yes
  supervisorctl:
    name: pdf_gen
    state: restarted

- name: Create tempCleaner.py script
  template: 
    src: usr/local/bin/tempCleaner.py
    dest: /usr/local/bin/tempCleaner.py
    owner: www-data
    group: www-data
    mode: 0755

- name: Create tempCleaner daily cronjob
  template: 
    src: etc/cron.daily/tempCleaner
    dest: /etc/cron.daily/tempCleaner
    mode: 0755

