---
# Configure PDF Generation

- name: configure pdf_gen in supervisor
  become: yes
  template:
    src: etc/supervisor/conf.d/pdf_gen.conf
    dest: "/etc/supervisor/conf.d/pdf_gen.conf"
    mode: 0644
  register: supervisor_conf_for_pdf_gen
  notify:
    - reload supervisord

- name: restart pdf_gen
  when: not supervisor_conf_for_pdf_gen|changed
  become: yes
  supervisorctl:
    name: pdf_gen
    state: restarted

- name: Add /etc/tmpfiles.d/cnx_tmp.conf to clean up /tmp
  become: yes
  template: 
    src: etc/tmpfiles.d/cnx_tmp.conf.j2
    dest: /etc/tmpfiles.d/cnx_tmp.conf
    owner: root
    group: root
    mode: 0644
