---
root_prefix: ""
_host_prefix: content02

archive_db_name: "{{ vault_archive_db_name }}"
archive_db_user: "{{ vault_archive_db_user }}"
archive_db_password: "{{ vault_archive_db_password }}"
archive_db_host: "{{ _host_prefix }}.cnx.org"
archive_db_port: 5432

publishing_broker_user: cnxpublishing
publishing_broker_password: cnxpublishing

memcached_hosts: localhost

varnish_port: 8990
haproxy_zcluster_port: 8998

archive_host: "{{ _host_prefix }}.cnx.org"
publishing_host: "{{ _host_prefix }}.cnx.org"
authoring_host: "{{ _host_prefix }}.cnx.org"
zclient_base_port: 8280
zclient_count: 1

zope_domain: "legacy-{{ _host_prefix }}.cnx.org"
arclishing_domain: "archive-{{ _host_prefix }}.cnx.org"
frontend_domain: "{{ _host_prefix }}.cnx.org"
accounts_domain: accounts-qa1.openstax.org
tutor_domain: tutor-qa.openstax.org
exercises_domain: exercises-qa.openstax.org

accounts_consumer_token: "{{ vault_accounts_consumer_token }}"
accounts_consumer_secret: "{{ vault_accounts_consumer_secret }}"
accounts_disable_verify_ssl: no

exercises_token: "{{ vault_exercises_token }}"

postgres_connections: "{{ vault_postgres_connections }}"

slack_token: "{{ vault_slack_token }}"

nfs_server_for_files1: "{{ _host_prefix }}.cnx.org"
nfs_server_for_files2: "{{ _host_prefix }}.cnx.org"
nfs_server_for_specials: "{{ _host_prefix }}.cnx.org"

webview_version: v0.24.0

princexml_deb_url: "http://www.princexml.com/download/prince_11-1_ubuntu16.04_amd64.deb"
