---
root_prefix: ""

archive_db_name: "{{ vault_archive_db_name }}"
archive_db_user: "{{ vault_archive_db_user }}"
archive_db_password: "{{ vault_archive_db_password }}"
archive_db_host: staging09.cnx.org
archive_db_port: 5432

publishing_broker_user: "{{ vault_publishing_broker_user }}"
publishing_broker_password: "{{ vault_publishing_broker_password }}"

memcached_hosts: localhost

varnish_port: 80

# Points to the haproxy running on tundra
archive_base_port: "{{ default_archive_base_port }}"
# Points to the publishing instance running on tundra
publishing_base_port: "{{ default_publishing_base_port }}"
zclient_base_port: "{{ default_zclient_base_port }}"

zope_domain: legacy-staging.cnx.org
arclishing_domain: archive-staging.cnx.org
frontend_domain: staging.cnx.org
accounts_domain: accounts-stage1.openstax.org
tutor_domain: tutor-staging.openstax.org
exercises_domain: exercises-staging.openstax.org

# See group_vars/all.yml for defaults
graylog_server: "{{ default_graylog_server }}"
graylog_port: 5143

accounts_consumer_token: "{{ vault_accounts_consumer_token }}"
accounts_consumer_secret: "{{ vault_accounts_consumer_secret }}"
accounts_disable_verify_ssl: no

exercises_token: "{{ vault_exercises_token }}"

postgres_connections: "{{ vault_postgres_connections }}"

slack_token: "{{ vault_slack_token }}"

archive_exports_directories:
  - files3
  - files
  - files2
  - files4

nfs_mounts:
  - name: /var/www/files
    src: /var/www/files
    server: staging-files00.cnx.org
  - name: /var/www/files2
    src: /var/www/files2
    server: staging-files00.cnx.org
  - name: /var/www/files3
    src: /var/www/files3
    server: staging-files01.cnx.org
  - name: /var/www/files4
    src: /var/www/files4
    server: staging-files01.cnx.org
  - name: /var/www/specials
    src: /var/www/specials
    server: staging-files00.cnx.org
  - name: /var/www/varnish_logs
    src: /var/www/varnish_logs
    server: staging-files00.cnx.org

nfs_connections: "{{ vault_nfs_connections }}"

webview_version: v0.23.3

blocked_ip_addresses: "{{ vault_blocked_ip_addresses }}"

princexml_deb_url: "http://www.princexml.com/download/prince_11-1_ubuntu16.04_amd64.deb"
