---
# Installs and configures Postgres.

- name: add apt-key for pgdg repository
  become: yes
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add pgdg repository
  become: yes
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    update_cache: yes

- name: install postgres
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "postgresql-{{ postgres_version }}"
    - "postgresql-server-dev-{{ postgres_version }}"
    - "postgresql-client-{{ postgres_version }}"
    - "postgresql-contrib-{{ postgres_version }}"
    # We'll assume plpython is required...
    - "postgresql-plpython-{{ postgres_version }}"
  notify:
    - restart postgresql
    
# +++
# Configure
# +++

- name: configure postgres role connection trust
  become: yes
  template:
    src: etc/postgresql/_/main/pg_hba.conf
    dest: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0640
  notify:
    - reload postgresql

- name: allow remote connections to the database
  become: yes
  lineinfile:
    dest: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    regexp: "^#?listen_addresses = '(localhost|\\*)'\\s.*$"
    line: "listen_addresses = '*'"
  notify:
    - reload postgresql
