---
# Installs and configures Postgres.

- name: install postgres
  become: yes
  apt:
    name:
      - "postgresql-{{ postgres_version }}"
      - "postgresql-server-dev-{{ postgres_version }}"
      - "postgresql-client-{{ postgres_version }}"
      - "postgresql-contrib-{{ postgres_version }}"
      # We'll assume plpython is required...
      - "postgresql-plpython-{{ postgres_version }}"
    state: present


  notify:
    - restart postgresql

- name: enable postgres
  become: yes
  service:
    name: "postgresql@{{ postgres_version }}-main.service"
    state: started
    enabled: yes
  tags:
    - postgres-enable

# +++
# Configure
# +++

- name: gather facts from db_connected
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: yes
  with_items:
    - "{{ groups.db_connected }}"
    - "{{ groups.replicant }}"

- name: configure postgres role connection trust
  become: yes
  template:
    src: etc/postgresql/_/main/pg_hba.conf
    dest: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0640
  notify:
    - restart postgresql

- name: configure postgresql.conf to include replication
  become: yes
  template:
    src: etc/postgresql/_/main/postgresql.conf
    dest: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0640
  notify:
    - reload postgresql
